version: 2.1

executors:
    my-executor:
        docker:
            -   image: circleci/python:3.7.3

jobs:
    build:
        executor: my-executor

        steps:
            - checkout

            -   run:
                    name: Create virtual environment
                    command: |
                        python3 -m venv venv

            -   run:
                    name: Install dependencies
                    command: |
                        . venv/bin/activate
                        pip3 install --progress-bar off --upgrade pip setuptools
                        pip3 install --progress-bar off .
                        pip3 install --progress-bar off -r test_requirements.txt

            -   persist_to_workspace:
                    root: .
                    paths:
                        - .

    test:
        executor: my-executor

        steps:
            -   attach_workspace:
                    at: .

            -   run:
                    name: Activate test environment
                    command: . venv/bin/activate

            -   run:
                    name: Running mypy
                    command: |
                        . venv/bin/activate
                        python3 -m mypy impute

            -   run:
                    name: Running pylint
                    command: |
                        . venv/bin/activate
                        python3 -m pylint impute

            -   run:
                    name: Running pytest
                    command: |
                        . venv/bin/activate
                        python3 -m pytest impute

workflows:
    version: 2
    build_and_test:
        jobs:
            -   build:
                    filters:
                        branches:
                            only:
                                - master

            -   test:
                    requires:
                        - build
                    filters:
                        branches:
                            only:
                                - master
